version: "3.8"
services:
  pixart:
    container_name: pixart
    image: pixart:latest
    build:
      context: .
    ports:
      - 12345:12345
    environment:
      - APP_CONTEXT=1024 #1024, 512, LCM
    tmpfs:
      - /tmp      
    volumes:
      - ./docker/cache/gradio:/workspace/gradio_cached_examples/30:rw
      - ./docker/cache/huggingface:/root/.cache/huggingface:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

